
version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:5000/api
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      MONGO_URI: mongodb://mongo:27017/financebox
      JWT_SECRET: supersecret
    restart: unless-stopped

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
